// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA69-qoOSwcnazoc91IjGG81ivNe0EjgeQ',
    appId: '1:532961649364:web:19dce5763c438f81851141',
    messagingSenderId: '532961649364',
    projectId: 'doctor-hunt-d700f',
    authDomain: 'doctor-hunt-d700f.firebaseapp.com',
    storageBucket: 'doctor-hunt-d700f.firebasestorage.app',
    measurementId: 'G-Z9E7GN8S7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJhnjF8QY4mbuARsTyDa_s4LM6fOCHwjU',
    appId: '1:532961649364:android:40e9fdec4fd097bf851141',
    messagingSenderId: '532961649364',
    projectId: 'doctor-hunt-d700f',
    storageBucket: 'doctor-hunt-d700f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZRQrNto5g2-IyuDekU-rFRHz4PkwKv24',
    appId: '1:532961649364:ios:348772f0ad5aa7d6851141',
    messagingSenderId: '532961649364',
    projectId: 'doctor-hunt-d700f',
    storageBucket: 'doctor-hunt-d700f.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZRQrNto5g2-IyuDekU-rFRHz4PkwKv24',
    appId: '1:532961649364:ios:348772f0ad5aa7d6851141',
    messagingSenderId: '532961649364',
    projectId: 'doctor-hunt-d700f',
    storageBucket: 'doctor-hunt-d700f.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA69-qoOSwcnazoc91IjGG81ivNe0EjgeQ',
    appId: '1:532961649364:web:827e2fff6c09d2b3851141',
    messagingSenderId: '532961649364',
    projectId: 'doctor-hunt-d700f',
    authDomain: 'doctor-hunt-d700f.firebaseapp.com',
    storageBucket: 'doctor-hunt-d700f.firebasestorage.app',
    measurementId: 'G-143VK9SEF8',
  );
}
